# Generated by Django 5.2.11 on 2026-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("road_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictiontask",
            name="input_file",
            field=models.FileField(upload_to="upload_road/"),
        ),
        migrations.AlterField(
            model_name="predictiontask",
            name="output_file",
            field=models.FileField(blank=True, null=True, upload_to="outputs_road/"),
        ),
    ]
