# Generated by Django 5.2.11 on 2026-06-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("road_app", "0002_alter_predictiontask_input_file_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PredictionTask",
            new_name="RoadDetection",
        ),
        migrations.AlterModelTable(
            name="roaddetection",
            table="road_app_predictiontask",
        ),
    ]
