# Generated by Django 5.2.11 on 2026-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("road_app", "0003_rename_predictiontask_roaddetection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roaddetection",
            name="error",
        ),
        migrations.RemoveField(
            model_name="roaddetection",
            name="input_file",
        ),
        migrations.RemoveField(
            model_name="roaddetection",
            name="output_file",
        ),
        migrations.RemoveField(
            model_name="roaddetection",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="roaddetection",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="footprint_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="uploads_road/"),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="result",
            field=models.ImageField(blank=True, null=True, upload_to="results_road/"),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="result_raster",
            field=models.FileField(blank=True, null=True, upload_to="results_road/"),
        ),
        migrations.AddField(
            model_name="roaddetection",
            name="shapefile_zip",
            field=models.FileField(blank=True, null=True, upload_to="results_road/"),
        ),
        migrations.AlterField(
            model_name="roaddetection",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.AlterModelTable(
            name="roaddetection",
            table=None,
        ),
    ]
