# Generated by Django 5.2.11 on 2026-06-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BuildingTask",
            new_name="BuildingDetection",
        ),
        migrations.AlterModelTable(
            name="buildingdetection",
            table="building_app_buildingtask",
        ),
    ]
