# Generated by Django 5.2.11 on 2026-06-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building_app", "0002_rename_buildingtask_buildingdetection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildingdetection",
            old_name="input_file",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="buildingdetection",
            name="error",
        ),
        migrations.RemoveField(
            model_name="buildingdetection",
            name="output_file",
        ),
        migrations.RemoveField(
            model_name="buildingdetection",
            name="progress",
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="footprint_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="result",
            field=models.ImageField(blank=True, null=True, upload_to="results/"),
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="result_raster",
            field=models.FileField(blank=True, null=True, upload_to="results/"),
        ),
        migrations.AddField(
            model_name="buildingdetection",
            name="shapefile_zip",
            field=models.FileField(blank=True, null=True, upload_to="results/"),
        ),
        migrations.AlterField(
            model_name="buildingdetection",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.AlterModelTable(
            name="buildingdetection",
            table=None,
        ),
    ]
