# Generated by Django 5.2.11 on 2026-06-08 08:57

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="change_detection_with_building_footprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_2023",
                    models.FileField(
                        upload_to="uploads/",
                        validators=[myapp.models.validate_file_extension],
                    ),
                ),
                (
                    "uploaded_2025",
                    models.FileField(
                        upload_to="uploads/",
                        validators=[myapp.models.validate_file_extension],
                    ),
                ),
                (
                    "result_png",
                    models.FileField(
                        upload_to="images_upload/",
                        validators=[myapp.models.validate_file_extension],
                    ),
                ),
                ("result_tif", models.FileField(upload_to="images_upload/")),
                ("result_shp", models.FileField(upload_to="images_upload/")),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "footprint_old_status",
                    models.CharField(default="pending", max_length=20),
                ),
                (
                    "footprint_new_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("footprint_old_progress", models.IntegerField(default=0)),
                ("footprint_new_progress", models.IntegerField(default=0)),
                (
                    "footprint_old",
                    models.FileField(blank=True, null=True, upload_to="footprints/"),
                ),
                (
                    "footprint_new",
                    models.FileField(blank=True, null=True, upload_to="footprints/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpatialJoinResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_shapefile", models.FileField(upload_to="shapefiles/")),
                ("change_shapefile", models.FileField(upload_to="shapefiles/")),
                ("result_shapefile", models.FileField(upload_to="output/")),
                (
                    "result_excel",
                    models.FileField(
                        upload_to="output/",
                        validators=[myapp.models.validate_file_extension],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Building_footprint",
        ),
    ]
