# Generated by Django 5.2.11 on 2026-06-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_change_detection_with_building_footprint_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
        migrations.DeleteModel(
            name="Road_Detection",
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
    ]
