# Generated by Django 5.2.11 on 2026-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="uploads_tree/"),
                ),
                (
                    "result",
                    models.ImageField(blank=True, null=True, upload_to="results_tree/"),
                ),
                (
                    "result_raster",
                    models.FileField(blank=True, null=True, upload_to="results_tree/"),
                ),
                (
                    "shapefile_zip",
                    models.FileField(blank=True, null=True, upload_to="results_tree/"),
                ),
                (
                    "stats_csv",
                    models.FileField(blank=True, null=True, upload_to="results_tree/"),
                ),
                ("footprint_count", models.PositiveIntegerField(default=0)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                (
                    "progress_message",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="TreePredictionTask",
        ),
    ]
